project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - articles/**.{qmd,md,ipynb}
    - resources/**.{qmd,md,ipynb}
  resources:
    - assets/**            # ensure local fonts, icons, images are copied
    - resources/**         # optional: keep downloads/attachments

website:
  title: "Syntax & Empathy"
  site-url: "https://syntax-and-empathy.github.io/s-and-e-hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles/
        text: Articles
      - href: resources/
        text: Resources
      - href: about.qmd
        text: About
  search: true
  page-footer:
    center: |
      © 2025 Syntax & Empathy — [Licensed under CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true
    smooth-scroll: true
    code-copy: true
    anchor-sections: true
    from: markdown+hard_line_breaks

execute:
  freeze: auto

metadata-files: []
