project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - articles/**.{qmd,md,ipynb}
    - resources/**.{qmd,md,ipynb}
  resources:
    - assets/**            # ensure local fonts, icons, images are copied
    - resources/**         # optional: keep downloads/attachments

website:
  title: "Syntax & Empathy"
  site-url: "https://syntaxandempathy.github.io/s-and-e-hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles/
        text: Articles
      - href: resources/
        text: Resources
      - href: about.qmd
        text: About
  search: true
  page-footer:
    center: |
      © {date:YYYY} Syntax & Empathy

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true
    smooth-scroll: true
    code-copy: true
    anchor-sections: true
    include-in-header:
      - _includes/fonts-preload.html   # uses absolute path with /syntax-and-empathy/

execute:
  freeze: auto

metadata-files: []
