title: 'Algorithmic Theatre: Exposing the Illusion of AI Writing Analysis'
tagline: 'A tale of two trackers: Python''s computational struggle and the deceptive
  simplicity of a browser-based facade.'
tldr:
- Failed attempts to build an AI writing analysis tool using Python revealed significant
  technical hurdles.
- A seemingly polished HTML/JavaScript tracker proved deceptively simple, masking
  a lack of substance.
- The experience highlights the challenges of transparently measuring human vs. AI
  contributions in writing.
link: null
synopsis: This series documents the author's journey to create a reliable system for
  tracking human and AI contributions in writing.  Early attempts using Python's computational
  power failed, followed by a surprisingly misleading experience with a simple browser-based
  interface that lacked actual analysis. The project ultimately explores the complexities
  of achieving true transparency in AI-assisted writing.
tags: AI writing, transparency, ethical AI, Python, JavaScript, HTML, analysis
audience: Writers, researchers, developers interested in AI writing tools
updated: 2025-09-03
