title: 'The Count That Couldn''t: A Cautionary Tale of AI-Assisted Writing'
tagline: When a good idea collapses under its own weight – a five-part series.
tldr:
- Failed initial attempt to build an AI-human contribution tracker after 45 hours.
- Started with simple JSON, spiraled into complex Python code.
- Lessons learned about planning and realistic AI capabilities.
link: null
synopsis: This five-part series documents the author's attempts to create a tool for
  measuring human contributions to AI-generated text.  The first part details the
  initial, ultimately unsuccessful, effort, highlighting the challenges of scaling
  a simple JSON-based approach and the unexpected complexities encountered when integrating
  AI and Python. It serves as a cautionary tale about the importance of careful planning
  and understanding the limitations of AI.
tags:
- AI
- writing
- tool building
- Python
- JSON
- failure
- case study
audience: Developers, writers, anyone interested in AI-assisted writing
updated: 2025-09-03
