title: 'The Count That Couldn''t: A Cautionary Tale of AI-Assisted Writing'
tagline: When a good idea collapses under its own weight – a five-part series.
tldr:
- Failed initial attempt to build an AI-human contribution tracker after 45 hours.
- Started with simple JSON, spiraled into complex Python code.
- Lessons learned about planning and realistic AI capabilities.
link: null
synopsis: This five-part series documents the author's attempts to create a tool for
  measuring human contributions to AI-generated text. The first part details the initial,
  ultimately unsuccessful, effort, highlighting the challenges of scaling a simple
  JSON-based approach and the unexpected complexities encountered when integrating
  AI and Python. It serves as a cautionary tale about the importance of careful planning
  and realistic expectations when using AI for complex tasks.
tags:
- AI
- writing
- programming
- Python
- JSON
- productivity
- failure
audience: Developers, writers, anyone interested in AI tools and their limitations.
updated: 2025-09-03
