title: 'A Year of AI: Content Creation Experiments'
tagline: Tracking AI's progress in generating holiday content across 2024.
tldr:
- Documented AI content generation experiments across four quarters.
- Analyzed performance of various AI models in different tasks and contexts.
- Tracked model improvements and challenges over time.
link: ''
synopsis: This project followed the author's year-long experiment using AI to generate
  content about global holiday traditions.  Each quarter's reports detail the methodologies,
  challenges, and results of using different AI models, showcasing their evolution
  in content creation capabilities with minimal human intervention.
tags:
- AI
- Content Generation
- Experiment
- Machine Learning
- Holiday Traditions
- Year-Long Project
audience: Researchers, AI enthusiasts, content creators.
updated: 2025-09-03
