title: 'The Count That Couldn''t: A Cautionary Tale of AI-Assisted Writing'
tagline: When a good idea collapses under its own weight — a five-part series.
tldr:
- Failed initial attempt to build an AI content contribution tracker (45 hours).
- Switched from JSON/XML to Python, despite lack of expertise.
- Lessons learned about planning and realistic expectations with AI.
link: null
synopsis: This five-part series documents the author's attempts to create a tool for
  measuring human contributions to AI-generated text.  The first part details the
  initial, ultimately unsuccessful, effort, highlighting the challenges of scaling
  a simple JSON-based approach and the unexpected complexities encountered when integrating
  AI and Python. It serves as a cautionary tale about the importance of careful planning
  and realistic assessment of AI capabilities.
tags:
- AI
- writing
- tooling
- Python
- JSON
- case study
- failure
audience: Developers, writers, anyone using AI writing tools
updated: 2025-09-03
