name: quarto-publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: quarto-pages
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto (pinned)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # Pin to a known-good stable release to avoid 'latest' 404s
          version: "1.7.33"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          uv --version

      - name: Cache uv + venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync Python environment (from uv.lock)
        run: |
          uv venv
          if [ -f uv.lock ]; then
            uv sync
          else
            uv lock
            uv sync
          fi
          echo "QUARTO_PYTHON=$GITHUB_WORKSPACE/.venv/bin/python" >> "$GITHUB_ENV"

      - name: Clean build
        run: quarto render --clean

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload preview artifact (PRs only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: site-preview
          path: _site
          retention-days: 3

      - name: Publish to gh-pages (main only)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
