name: README Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "auto"
        type: choice
        options: [auto, full, stale, target]
      target_dir:
        description: "Directory to process when mode=target (relative to repo root)"
        required: false
        default: ""
      stale_days:
        description: "Consider README stale if content newer by this many days"
        required: false
        default: "30"
      dry_run:
        description: "Do not write files; just log"
        type: boolean
        default: false
      ai_enrich:
        description: "Use Gemini to create/update meta.yml"
        type: boolean
        default: false
      overwrite_meta:
        description: "Allow overwriting existing meta.yml"
        type: boolean
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run sync
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python tools/readme/readme_sync.py             --mode "${{ github.event.inputs.mode || 'auto' }}"             --target-dir "${{ github.event.inputs.target_dir || '' }}"             --stale-days "${{ github.event.inputs.stale_days || '30' }}"             ${{ github.event.inputs.dry_run && '--dry-run' || '' }}             ${{ github.event.inputs.ai_enrich && '--ai-enrich' || '' }}             ${{ github.event.inputs.overwrite_meta && '--overwrite-meta' || '' }}

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(readme-sync): update READMEs and meta"
          git push
