name: README Sync (Gemini Direct)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (manual)"
        required: true
        default: "full"
        type: choice
        options: [full, target]
      target_dir:
        description: "Directory to process when mode=target (relative to repo root)"
        required: false
        default: ""
      dry_run:
        description: "Do not write files; just log"
        type: boolean
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate READMEs
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python tools/readme/readme_sync.py             --mode "${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.mode || 'full') || 'auto' }}"             --target-dir "${{ github.event.inputs.target_dir || '' }}"             ${{ github.event.inputs.dry_run && '--dry-run' || '' }}

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(readme-sync): regenerate README.md files"
          git push
