name: GEMINI:readme-sync

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'           # prevent infinite loop on bot commits
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        required: true
        default: "auto"
        type: choice
        options: [auto, full, target]
      target_dir:
        description: "Directory to process when mode=target (relative to repo root)"
        required: false
      dry_run:
        description: "Do not write files"
        required: true
        default: "false"
        type: choice
        options: [false, true]

permissions:
  contents: write

jobs:
  readme_sync:
    runs-on: ubuntu-latest
    concurrency:
      group: readme-sync
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate READMEs
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_SHA:    ${{ github.sha }}
        run: |
          set -e
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MODE="${{ github.event.inputs.mode }}"
            TARGET="${{ github.event.inputs.target_dir }}"
            DRY="${{ github.event.inputs.dry_run }}"
          else
            MODE="auto"
            TARGET=""
            DRY="false"
          fi

          echo "mode=$MODE target=$TARGET dry_run=$DRY"
          python tools/readme/readme_sync.py \
            --mode "$MODE" \
            $([ -n "$TARGET" ] && echo --target-dir "$TARGET") \
            $([ "$DRY" = "true" ] && echo --dry-run)

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add **/README.md
          if git diff --cached --quiet; then
            echo "No README changes to commit."
            exit 0
          fi
          git commit -m "chore(readme-sync): regenerate README.md files"
          git push
