name: README Sync

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/**"
      - "templates/**"
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose how to run"
        required: true
        default: "auto"
        type: choice
        options: [auto, full, stale, target]
      target_dir:
        description: "Path for mode=target (recursive)"
        required: false
        type: string
      full_rewrite_enabled:
        description: "Allow full rewrite (safety toggle for mode=full)"
        required: false
        default: false
        type: boolean
      dry_run:
        description: "Preview only (no writes)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install Jinja2 PyYAML

      - name: Run sync
        run: |
          python scripts/generate_readmes.py \
            --mode "${{ github.event.inputs.mode || 'auto' }}" \
            --target-dir "${{ github.event.inputs.target_dir || '' }}" \
            --full-rewrite-enabled "${{ github.event.inputs.full_rewrite_enabled && 'true' || 'false' }}" \
            --dry-run "${{ github.event.inputs.dry_run && 'true' || 'false' }}"

      - name: Commit & push if changed
        run: |
          set -e
          # Stage new/modified README.md files (root + nested)
          git ls-files -o -m --exclude-standard | awk '/(^|\/)README\.md$/' | xargs -r git add
          # Also include modified tracked README.md files
          git add -u

          if [[ -n "$(git diff --cached --name-only)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(readme): sync via action [skip ci]"
            git push
          else
            echo "No README changes to commit."
          fi